### ISSUE TITLE
Can I get ban for using this app?

### ISSUE THREAD

**Issue by khojabergen** [SebastienDuruz/Eve-Intel-Checker#1]
Can I get ban for using this app?

**Comment by SebastienDuruz** [comment]
Hello,

I don't think there is any risk of a ban for using this app.
There is no weird process, the application just reads a log file generated by the game and parses the results.
However, I will contact CCP to confirm that and put the information in the README file.

Thanks for asking

**Comment by khojabergen** [comment]
Please write here after CCP answers. Big thanks.

**Comment by khojabergen** [comment]
any updates?

**Comment by SebastienDuruz** [comment]
I did a demand on 24 september but still nothing new, will write here as soon as I get an answer.

**Comment by SebastienDuruz** [comment]
## French answer
![image](https://user-images.githubusercontent.com/40761875/194924603-c6a1df04-bbd6-403a-b70e-775d64005965.png)
## English traducted answer
[...]
We do not endorse or condone the use of player-created software or any other third-party application or software that gives players an unfair advantage. We may, at our discretion, condone the use of apps or other software that simply enhance player enjoyment in a way that maintains fair gameplay. However, if any third-party application or other software is used to gain an improper advantage, or is used for purposes beyond its intended use, or if the application or other software violates other parts of the EULA, we can fully enforce our rights to prohibit such use, including player bans. Please use player-made software or other third-party software at your own risk.
 
There are programs created by gamers that behave similarly and do much more than you intend with yours, and while we have taken no action against these programs, that does not mean that we explicitly allow them. Again, please create and use software like this at your own risk.
[...]
## What i conclude
So it's not a "supported" way of using the chat logfiles but as there is a lot of tools doing same or more than EveIntelChecker (still up after some years), I don't think there is any risk of using this app (for now at least).
By the way, if any changes appears, I'll update here.
It's up to you to use it or not but I don't think there's any risk as there is nothing that interact with the game client, it just reads a text file and don't give huge advantage to the players.

At least it's my point of view.
