### ISSUE TITLE
Stuck on "Attempting to reconnect to the server"

### ISSUE THREAD

**Issue by JRivera17** [SebastienDuruz/Eve-Intel-Checker#9]
Title says it all. If you have any ideas as to what the issue might be, that would be great. Thanks!

![image](https://user-images.githubusercontent.com/13386596/235549039-19255ce1-1cf9-4a41-9f43-c6d73ced6462.png)

**Comment by SebastienDuruz** [comment]
Hello,

I never had this issue, but as far as I know it's probably caused by a rights issue that cause the backend of the app to crash.
You can try to uninstall the application and reinstall it for only one user (also, use the default installation folder) :
![image](https://user-images.githubusercontent.com/40761875/235588927-ba52cfb2-8c91-40f0-97e2-66b2bd735340.png)

If this doesn't works, could you please give me the Operating System you are using and the action you were doing when the issue appends ?

**Comment by JRivera17** [comment]
Could be the fact that I moved the folder out of the default option, I'll
check it and get back to you. Thanks!

**Comment by JRivera17** [comment]
Err, before I mess with it too much, could you confirm which one is the
default folder, thanks!

**Comment by SebastienDuruz** [comment]
The default folder looks like :
`C:\Users\USERNAME\AppData\Local\Programs\EveIntelChecker`

If you uninstall and re-use the installer, it should be the default path provided by the installer.

**Comment by JRivera17** [comment]
I just checked, it's installed in the right place and still giving the same
error. I have never used the app before, so the action I was trying to
perform was "launching the app"; it happened after I selected a text file.
Now, it won't even allow me to do anything--even when I uninstall and
reinstall the app. It just goes straight to "Attempting to reconnect to the
server".

My OS is Windows Version 10.0.19044 Build 19044

**Comment by SebastienDuruz** [comment]
Thanks for the complementary informations,

Another test you can do :

- Make sure EveIntelChecker is **closed**
- Delete the files `userSettings_1.json` and `userSettings_2.json` contains in the folder `C:\Users\USERNAME\AppData\Local\EveIntelChecker`
- Start EveIntelChecker

**Comment by JRivera17** [comment]
No dice unfortunately. I deleted the files and reopened the program, and I was able to select my system (no issue yet), but when I selected a channel to monitor, the application goes into the "Attempting to reconnect to the server" mode, and is no longer usable (I can't click anything in the application).

**Comment by SebastienDuruz** [comment]
It looks like the issue appears when you start the reading process, the initial load of the file works (because the top label is updated on your screenshot) but after that, the backend crashes for any reason. 

I'wasn't able to reproduce the bug, I'll do more testing and coming back to you.

**Comment by JRivera17** [comment]
No worries, thanks for your help! I'll try debugging on this side too and
I'll let you know if I find something.

**Comment by SebastienDuruz** [comment]
Hello @JRivera17,

Sorry for getting back so late, I've been very busy these past few weeks.

I've made some attempts to reproduce the error on a Windows 10 virtual machine. I could only throw an error when the `C:\Users\USERNAME\Documents\EVE\logs\Chatlogs` folder does not exists.

![image](https://github.com/SebastienDuruz/Eve-Intel-Checker/assets/40761875/650c5776-8678-483e-b641-e2897c925927)

Can you make sure the folder exists and that you are selecting the text file from that folder ?

If the problem persists, you can check the **event viewer** for **.NET Runtime** errors :
- Search for *event viewer* on the windows task bar and open it
![image](https://github.com/SebastienDuruz/Eve-Intel-Checker/assets/40761875/d1abf934-6f11-483a-b8bb-2cf0acf8cd62)
- Select **Windows Logs** -> **Applications** and look for **.NET Runtime** error related to **EveIntelChecker**
![image](https://github.com/SebastienDuruz/Eve-Intel-Checker/assets/40761875/59c7b534-a66c-4a57-ba6e-489c51606300)
- Post the content of the bug in this thread
![image](https://github.com/SebastienDuruz/Eve-Intel-Checker/assets/40761875/de22fecf-fb8d-460f-8678-a956a4ce9e55)

**Comment by JRivera17** [comment]
Hi Sebastien,

I'll give it a whirl once I'm back home! Thanks for your help!

No worries if we never figure it out though, I managed to find my old
laptop which still had near2 installed, so I managed to port it over to my
PC, and it's been working ever since.

Thanks again for your help, I'll get back to you when I get a chance to
troubleshoot.
